pendanaan/urls.py
from django.urls import path
# from django.conf import settings
# from django.conf.urls.static import static
from .views import *

app_name = 'pendanaan'

urlpatterns = [
    path("", index, name="index"),
    path("api/", get_umkm, name="api_umkm"),
    path("api-view/", view_umkm_flutter, name="api_view"),
    path("api-global/", view_all_umkm_flutter, name="api_global"),
    path("api-add/", add_umkm_flutter, name="api_add"),
    path("add/", add_umkm, name="add_umkm"),
    path("view/", view_umkm, name="view_umkm")
]

users/urls.py
# from django.urls import path, include

# from .views import user_login, user_logout, user_register

# urlpatterns = [
#     path('login', user_login, name = 'login'),
#     path('logout', user_logout, name = 'logout'),
#     path('register', user_register, name = 'register'),
# ]

# app_name = 'users'

from django.urls import path
from users.views import *

app_name = 'users'

urlpatterns = [
    path('login/', signin, name="login"),
    path('register/', signup, name="register"),
    path('signout/', signout, name="signout"),
    path('loginflutter', loginFlutter, name='loginFlutter'),
    path('registerflutter', registerFlutter, name='registerFlutter'),
    path('logoutflutter',logoutFlutter,name='logoutFlutter'),
]

yukinvest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import homepage.urls as homepage
import pendanaan.urls as pendanaan
import profil.urls as profil
import infoumkm.urls as infoumkm
import adminpage.urls as adminpage
import users.urls as users
import pasar_saham.urls as pasarsaham

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(homepage)),
    path('pendanaan/', include(pendanaan)),
    path('info/', include(infoumkm)),
    path('profil/', include(profil)),
    path('adminpage/', include(adminpage)),
    path('daftarumkm/', include(infoumkm)),
    path('users/', include(users)),
    path('daftarumkm/', include(infoumkm)),
    path('pasarsaham/', include(pasarsaham)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pendanaan/models.py
from django.db import models
from django.contrib.auth.models import User

class UMKM(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    ACEH = 'Aceh'
    SUMATERA_UTARA = 'Sumatera Utara'
    SUMATERA_BARAT = 'Sumatera Barat'
    RIAU = 'Riau'
    KEPULAUAN_RIAU = 'Kepulauan Riau'
    JAMBI = 'Jambi'
    SUMATERA_SELATAN = 'Sumatera Selatan'
    BANGKA_BELITUNG = 'Kepulauan Bangka Belitung'
    BENGKULU = 'Bengkulu'
    LAMPUNG = 'Lampung'
    DKI_JAKARTA = 'DKI Jakarta'
    BANTEN = 'Banten'
    JAWA_BARAT = 'Jawa Barat'
    JAWA_TENGAH = 'Jawa Tengah'
    YOGYAKARTA = 'DI Yogyakarta'
    JAWA_TIMUR = 'Jawa Timur'
    BALI = 'Bali'
    NUSA_TENGGARA_BARAT = 'Nusa Tenggara Barat'
    NUSA_TENGGARA_TIMUR = 'Nusa Tenggara Timur'
    KALIMANTAN_BARAT = 'Kalimantan Barat'
    KALIMANTAN_TENGAH = 'Kalimantan Tengah'
    KALIMANTAN_SELATAN = 'Kalimantan Selatan'
    KALIMANTAN_TIMUR = 'Kalimantan Timur'
    KALIMANTAN_UTARA = 'Kalimantan Utara'
    SULAWESI_UTARA = 'Sulawesi Utara'
    GORONTALO = 'Gorontalo'
    SULAWESI_TENGAH = 'Sulawesi Tengah'
    SULAWESI_BARAT = 'Sulawesi Barat'
    SULAWESI_SELATAN = 'Sulawesi Selatan'
    SULAWESI_TENGGARA = 'Sulawesi Tenggara'
    MALUKU = 'Maluku'
    MALUKU_UTARA = 'Maluku Utara'
    PAPUA_BARAT = 'Papua Barat'
    PAPUA = 'Papua'

    PILIHAN_DOMISILI = [
        (ACEH, 'Aceh'),
        (SUMATERA_UTARA, 'Sumatera Utara'),
        (SUMATERA_BARAT, 'Sumatera Barat'),
        (RIAU, 'Riau'),
        (KEPULAUAN_RIAU, 'Kepulauan Riau'),
        (JAMBI, 'Jambi'),
        (SUMATERA_SELATAN, 'Sumatera Selatan'),
        (BANGKA_BELITUNG, 'Kepulauan Bangka Belitung'),
        (BENGKULU, 'Bengkulu'),
        (LAMPUNG, 'Lampung'),
        (DKI_JAKARTA, 'DKI Jakarta'),
        (BANTEN, 'Banten'),
        (JAWA_BARAT, 'Jawa Barat'),
        (JAWA_TENGAH, 'Jawa Tengah'),
        (YOGYAKARTA, 'DI Yogyakarta'),
        (JAWA_TIMUR, 'Jawa Timur'),
        (BALI, 'Bali'),
        (NUSA_TENGGARA_BARAT, 'Nusa Tenggara Barat'),
        (NUSA_TENGGARA_TIMUR, 'Nusa Tenggara Timur'),
        (KALIMANTAN_BARAT, 'Kalimantan Barat'),
        (KALIMANTAN_TENGAH, 'Kalimantan Tengah'),
        (KALIMANTAN_SELATAN, 'Kalimantan Selatan'),
        (KALIMANTAN_TIMUR, 'Kalimantan Timur'),
        (KALIMANTAN_UTARA, 'Kalimantan Utara'),
        (SULAWESI_UTARA, 'Sulawesi Utara'),
        (GORONTALO, 'Gorontalo'),
        (SULAWESI_TENGAH, 'Sulawesi Tengah'),
        (SULAWESI_BARAT, 'Sulawesi Barat'),
        (SULAWESI_SELATAN, 'Sulawesi Selatan'),
        (SULAWESI_TENGGARA, 'Sulawesi Tenggara'),
        (MALUKU, 'Maluku'),
        (MALUKU_UTARA, 'Maluku Utara'),
        (PAPUA_BARAT, 'Papua Barat'),
        (PAPUA, 'Papua')
    ]

    merek_bisnis = models.CharField(max_length=50)
    domisili = models.CharField(
	max_length=30,
	choices = PILIHAN_DOMISILI,
	default = ACEH
    )
    
    produk_jasa = models.CharField(max_length=30)
    saham_umkm = models.CharField(max_length=30)
    pendanaan_dibutuhkan = models.IntegerField()
    deskripsi = models.TextField()
    logo_usaha = models.ImageField(upload_to='Logo UMKM/')
    gambar_usaha = models.ImageField(upload_to='Foto UMKM/')
    ringkasan_perusahaan = models.FileField(upload_to='Ringkasan UMKM/')
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.merek_bisnis} {self.status}"


    

pendanaan/forms.py
from django.forms import ModelForm, widgets
from django.forms.widgets import Input, Select, Textarea, FileInput
from .models import UMKM

class UMKMForm(ModelForm):
    class Meta:
        model = UMKM
        fields = [
	    'merek_bisnis', 'domisili', 'produk_jasa', 'saham_umkm', 'pendanaan_dibutuhkan', 
	    'deskripsi', 'logo_usaha', 'gambar_usaha', 'ringkasan_perusahaan', 
	]

# 
# "type": "file",
        widgets = {
            "merek_bisnis": Input(attrs={"class": "form-control"}),
            "domisili": Select(attrs={"class": "form-control"}, choices=(UMKM.PILIHAN_DOMISILI)),
            "produk_jasa": Input(attrs={"class": "form-control"}),
	    "saham_umkm": Input(attrs={"class": "form-control"}),
            "pendanaan_dibutuhkan": Input(attrs={"type": "number", "class": "form-control"}),
            "deskripsi": Textarea(attrs={"class": "form-control"}),
            "logo_usaha": FileInput(attrs={"class": "form-control"}),
            "gambar_usaha": FileInput(attrs={"class": "form-control"}),
            "ringkasan_perusahaan": FileInput(attrs={"class": "form-control"}),	    
        }


  

pendanaan/views.py
from typing import final
from django.shortcuts import redirect, render
from pendanaan.forms import UMKMForm
from .models import UMKM
from django.core import serializers
from django.http.response import HttpResponse
from django.contrib.auth.decorators import login_required

from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
import json

def index(request):
    return render(request, "pendanaan/index_pendanaan.html")

# @login_required(login_url="users:login")
def view_umkm(request):
    obj = UMKM.objects.filter(request.user).get(pk=1)
    obj_dict = {"obj": obj}
    return render(request, "pendanaan/view_umkm.html", obj_dict)

# @login_required(login_url="users:login")
def get_umkm(request):
    umkm = UMKM.objects.filter(request.user).get(pk=1)
    umkm_json = serializers.serialize("json", umkm)
    return HttpResponse(umkm_json, content_type="application/json")

# @login_required(login_url="users:login")
def add_umkm(request):
    form = UMKMForm()
    umkm = UMKM.objects.filter(request.user).get(pk=1)
    if umkm:
        return redirect("pendanaan:view_umkm")
    elif request.method == "POST":
        data = request.POST.dict()
        data["user"] = request.user
        form = UMKMForm(data, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("pendanaan:view_umkm")
    context = {"form": form}
    return render(request, "pendanaan/add_umkm.html", context)

# @login_required(login_url='/login/')
def view_umkm_flutter(request):
    form_umkm = UMKMForm(request.POST or None)

    if request.method == "GET":
        umkm = UMKM.objects.filter(user=request.user)
        data = serializers.serialize("json", umkm)
        return HttpResponse(data, content_type="application/json")

    if request.method == "POST" and form_umkm.is_valid():
        form = form_umkm.save(commit=False)
        form.user = request.user
        form.save()
        
        umkm = UMKM.objects.filter(user=request.user).last()
        return JsonResponse({'user': str(request.user), 'nama': umkm.nama, 'deskripsi':umkm.deskripsi, 'logo_usaha': logo_usaha})
    
    return JsonResponse({'nama': "", 'deskripsi':"", 'logo_usaha': ""})

def view_all_umkm_flutter(request):
    form_umkm = UMKMForm(request.POST or None)

    if request.method == "GET":
        umkm = UMKM.objects.all()
        data = serializers.serialize("json", umkm)
        return HttpResponse(data, content_type="application/json")

    if request.method == "POST" and form_umkm.is_valid():
        form = form_umkm.save(commit=False)
        form.user = request.user
        form.save()
        
        umkm = UMKM.objects.all()
        return JsonResponse({'user': str(request.user), 'nama': kegiatan.nama, 'deskripsi':kegiatan.deskripsi})
    
    return JsonResponse({'nama': "", 'deskripsi':""})

@csrf_exempt
def add_umkm_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        nama = data["nama"]
        merek_bisnis  = data["merek_bisnis"]
        domisili = data["domisili"]
        produk_jasa = data["produk_jasa"]
        saham_umkm = data["saham_umkm"]
        pendanaan_dibutuhkan = data["pendanaan_dibutuhkan"]
        deskripsi = data["deskripsi"]
        logo_usaha = data["logo_usaha"]
	gambar_usaha = data["gambar_usaha"]
        ringkasan_perusahaan = data["ringkasan_perusahaan"]
        status = data["status"]

        form = UMKM(
            user = request.user,
            nama = nama,
            deskripsi = deskripsi,
            nama = nama,
            merek_bisnis  = merek_bisnis,
            domisili = domisili,
            produk_jasa = produk_jasa,
            saham_umkm = saham_umkm,
            pendanaan_dibutuhkan = pendanaan_dibutuhkan,
            deskripsi = deskripsi,
            logo_usaha = logo_usaha,
	    gambar_usaha = gambar_usaha,
            ringkasan_perusahaan = ringkasan_perusahaan,
            status = status
        )
        
        form.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

pendanaan/templates/pendanaan/add_umkm.html
{% extends 'base.html' %}

{% load static %}


{% block title %}Pengajuan Pendanaan{% endblock %}

  {% block meta %}
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="description">
  <meta content="" name="keywords">
  {% endblock meta %}

  {% block css %} 

  <!-- Favicons -->
  <link href={% static "pendanaan/img/favicon.jpg" %} rel="icon">
  <link href={% static "pendanaan/img/apple-touch-icon.jpg" %} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "pendanaan/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "pendanaan/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "pendanaan/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "pendanaan/vendor/boxicons/css/boxicons.min.css" %} rel="stylesheet">
  <link href={% static "pendanaan/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "pendanaan/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "pendanaan/css/style.css" %} rel="stylesheet">
  <link href={% static "pendanaan/css/add_umkm.css" %} rel="stylesheet">

  {% endblock css %}

  {% block content %}

  <main id="main" data-aos="fade-up">
    <section class="inner-page">
      <div class="container">
        <h3>
          Pengisian Formulir Pengajuan Pendanaan
        </h3>
        <form action="" method="POST" id="form-umkm" enctype="multipart/form-data">
        {% csrf_token %}
  	  <div class="row mb-3">
    	    <label for="merek_bisnis" class="col-sm-2 col-form-label">Merek Bisnis</label>
    	    <div class="col-sm-10">
      	    {{ form.merek_bisnis }}
    	    </div>
  	  </div>
  	  <div class="row mb-3">
    	    <label for="domisili" class="col-sm-2 col-form-label">Domisili</label>
    	    <div class="col-sm-10">
      	    {{ form.domisili }}
    	    </div>
  	  </div>
  	  <div class="row mb-3">
    	    <label for="produk_jasa" class="col-sm-2 col-form-label">Produk/Jasa</label>
    	    <div class="col-sm-10">
      	    {{ form.produk_jasa }}
    	    </div>
  	  </div>
  	   <div class="row mb-3">
    	    <label for="saham_umkm" class="col-sm-2 col-form-label">Saham UMKM</label>
    	    <div class="col-sm-10">
      	    {{ form.saham_umkm }}
    	    </div>
  	  </div>
  	  <div class="row mb-3">
    	    <label for="pendanaan_dibutuhkan" class="col-sm-2 col-form-label">Dana yang Dibutuhkan</label>
    	    <div class="col-sm-10">
      	    {{ form.pendanaan_dibutuhkan }}
    	    </div>
  	  </div>
  	  <div class="row mb-3">
    	    <label for="deskripsi" class="col-sm-2 col-form-label">Deskripsi</label>
    	    <div class="col-sm-10">
      	    {{ form.deskripsi }}
    	    </div>
  	  </div>
  	  <div class="row mb-3">
    	    <label for="logo_usaha" class="col-sm-2 col-form-label">Logo Usaha</label>
    	    <div class="col-sm-10">
      	    {{ form.logo_usaha }}
    	    </div>
  	  </div>
  	  <div class="row mb-3">
    	    <label for="gambar_usaha" class="col-sm-2 col-form-label">Foto Usaha</label>
    	    <div class="col-sm-10">
      	    {{ form.gambar_usaha }}
    	    </div>
  	  </div>
  	  <div class="row mb-3">
    	    <label for="ringkasan_perusahaan" class="col-sm-2 col-form-label">Ringkasan Bisnis Anda</label>
    	    <div class="col-sm-10">
      	    {{ form.ringkasan_perusahaan }}
    	    </div>
  	  </div>
  	  <button type="submit" class="btn btn-primary">Submit</button>
	</form>
      </div>
    </section>

  </main><!-- End #main -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

<!-- Vendor JS Files -->
  <script src={% static "pendanaan/vendor/aos/aos.js" %}></script>
  <script src={% static "pendanaan/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "pendanaan/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "pendanaan/vendor/isotope-layout/isotope.pkgd.min.js" %}></script>
  <script src={% static "pendanaan/vendor/php-email-form/validate.js" %}></script>
  <script src={% static "pendanaan/vendor/purecounter/purecounter.js" %}></script>
  <script src={% static "pendanaan/vendor/swiper/swiper-bundle.min.js" %}></script>
  <script src={% static "pendanaan/vendor/waypoints/noframework.waypoints.js" %}></script>

  <!-- Template Main JS File -->
  <script src={% static "pendanaan/js/main.js" %}></script>

  {% endblock content %}

pendanaan/templates/pendanaan/index_pendanaan.html
{% extends 'base.html' %}

{% load static %}


{% block title %}Pendanaan{% endblock %}

  {% block meta %}
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="description">
  <meta content="" name="keywords">
  {% endblock meta %}

  {% block css %} 

  <!-- Favicons -->
  <link href={% static "pendanaan/img/favicon.jpg" %} rel="icon">
  <link href={% static "pendanaan/img/apple-touch-icon.jpg" %} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "pendanaan/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "pendanaan/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "pendanaan/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "pendanaan/vendor/boxicons/css/boxicons.min.css" %} rel="stylesheet">
  <link href={% static "pendanaan/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "pendanaan/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "pendanaan/css/style.css" %} rel="stylesheet">

  {% endblock css %}

  {% block content %}

  <main id="main">
    <!-- ======= About Section ======= -->
    <section id="about" class="about section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-title">
          <h3>Bergabunglah Bersama <span>Yuk Invest</span></h3>
          <p>YukInvest hadir memberikan bantuan untuk mendorong masyarakat Indonesia untuk berinvestasi kepada UMKM demi memajukan perekonomian Indonesia.</p>
        </div>

        <div class="row">
          <div class="col-lg-6" data-aos="fade-right" data-aos-delay="100">
            <img src={% static "pendanaan/img/about.jpg" %} class="img-fluid" alt="">
          </div>
          <div class="col-lg-6 pt-4 pt-lg-0 content d-flex flex-column justify-content-center" data-aos="fade-up" data-aos-delay="100">
            <h3>Yuk Invest akan melakukan distribusi laporan keuangan bulanan dan dividen melalui sistem pendanaan kami.</h3>
            <p class="fst-italic">
             Saat ini kami fokus di industri waralaba (franchise), UMKM, Startup, dan Proyek. 
            </p>
            <ul>
              <li>
                <i class="bx bx-store-alt"></i>
                <div>
                  <h5>INVESTASI BISNIS BERSAMA</h5>
                  <p>Kamu dapat membuka bisnis UMKM secara bersama-sama hingga mendapatkan Legalitas PT</p>
                </div>
              </li>
              <li>
                <i class="bx bx-images"></i>
                <div>
                  <h5>DISTRIBUSI PROFIT BERKALA</h5>
                  <p>Mekanisme pembagian profit yang mudah. Diatur sesuai persentase kepemilikan saham secara otomatis melalui sistem Saldo Efek.</p>
                </div>
              </li>
            </ul>
          </div>
        </div>

      </div>
    </section><!-- End About Section -->

    <!-- ======= Testimonials Section ======= -->
    <section id="testimonials" class="testimonials">
      <div class="container" data-aos="zoom-in">

        <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper">

            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src={% static "pendanaan/img/testimonials/testimonials-1.jpg" %} class="testimonial-img" alt="">
                <h3>Nugraha</h3>
                <h4>Pemilik Warung Internet</h4>
                <p>
                  <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                  Yuk Invest sangat membantu kami dalam menjalankan usaha. Dengan Yuk Invest, saya dapat melengkapi perlengkapan yang dibutuhkan di Warnet seperti PC, Headset, dan lain-lain.
                  <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src={% static "pendanaan/img/testimonials/testimonials-2.jpg" %} class="testimonial-img" alt="">
                <h3>Aktwovhiday</h3>
                <h4>Pemiliki Kedai Makanan</h4>
                <p>
                  <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                  Alhamdulillah, Yuk Invest membuat kami memiliki modal dalam mengemban usaha.
                  <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src={% static "pendanaan/img/testimonials/testimonials-3.jpg" %} class="testimonial-img" alt="">
                <h3>Abdullah</h3>
                <h4>Pemilik Rental Mobil</h4>
                <p>
                  <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                  Usaha rental mobil memerlukan dana yang cukup besar. Semenjak ada Yuk Invest, semua masalah jadi teratasi.
                  <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
              </div>
            </div><!-- End testimonial item -->

            <div class="swiper-slide">
              <div class="testimonial-item">
                <img src={% static "pendanaan/img/testimonials/testimonials-4.jpg" %} class="testimonial-img" alt="">
                <h3>Gymnastiar</h3>
                <h4>Pengusaha Mebel</h4>
                <p>
                  <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                  Di zaman modern seperti ini, bisnis mebel lokal mulai terancam, bahan pun semakin mahal. Namun, Yuk Invest hadir sebagai penerang bagi kita dalam memulai usaha yang kita rintis.
                  <i class="bx bxs-quote-alt-right quote-icon-right"></i>
                </p>
              </div>
            </div><!-- End testimonial item -->
          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Testimonials Section -->

    

  </main><!-- End #main -->

  <!-- ======= Hero Section ======= -->
  <section id="hero" class="d-flex align-items-center">
    <div class="container" data-aos="zoom-out" data-aos-delay="100">
      <h1>Ajukan <span>Sekarang!</span></h1>
      <h2>Dengan mengisi form ini, Anda bisa mendapatkan modal ekspansi bisnis anda, dengan cara membagikan persentase kepemilikan saham Bisnis atau Outlet anda, kepada lebih dari 1.000 investor dari seluruh Indonesia.</h2>
      <div class="d-flex">
        <a href="{% url 'pendanaan:add_umkm' %}" class="btn-get-started scrollto">Ajukan</a>
      </div>
    </div>
  </section><!-- End Hero -->

  <!-- ======= Footer ======= 
  <footer id="footer">
    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright <strong><span>BizLand</span></strong>. All Rights Reserved
      </div>
    </div>
  </footer><!-- End Footer -->

  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src={% static "pendanaan/vendor/aos/aos.js" %}></script>
  <script src={% static "pendanaan/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "pendanaan/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "pendanaan/vendor/isotope-layout/isotope.pkgd.min.js" %}></script>
  <script src={% static "pendanaan/vendor/php-email-form/validate.js" %}></script>
  <script src={% static "pendanaan/vendor/purecounter/purecounter.js" %}></script>
  <script src={% static "pendanaan/vendor/swiper/swiper-bundle.min.js" %}></script>
  <script src={% static "pendanaan/vendor/waypoints/noframework.waypoints.js" %}></script>

  <!-- Template Main JS File -->
  <script src={% static "pendanaan/js/main.js" %}></script>

{% endblock content %}