profil/urls.py
from django.urls import path
from . import views

app_name = 'profil'

urlpatterns = [
    path('', views.datadiri_form, name = '')
]

users/urls.py
# from django.urls import path, include

# from .views import user_login, user_logout, user_register

# urlpatterns = [
#     path('login', user_login, name = 'login'),
#     path('logout', user_logout, name = 'logout'),
#     path('register', user_register, name = 'register'),
# ]

# app_name = 'users'

from django.urls import path
from users.views import *

app_name = 'users'

urlpatterns = [
    path('login/', signin, name="login"),
    path('register/', signup, name="register"),
    path('signout/', signout, name="signout"),
    path('loginflutter', loginFlutter, name='loginFlutter'),
    path('registerflutter', registerFlutter, name='registerFlutter'),
    path('logoutflutter',logoutFlutter,name='logoutFlutter'),
]

yukinvest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import homepage.urls as homepage
import pendanaan.urls as pendanaan
import profil.urls as profil
import infoumkm.urls as infoumkm
import adminpage.urls as adminpage
import users.urls as users
import pasar_saham.urls as pasarsaham

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(homepage)),
    path('pendanaan/', include(pendanaan)),
    path('info/', include(infoumkm)),
    path('profil/', include(profil)),
    path('adminpage/', include(adminpage)),
    path('daftarumkm/', include(infoumkm)),
    path('users/', include(users)),
    path('daftarumkm/', include(infoumkm)),
    path('pasarsaham/', include(pasarsaham)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profil/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE

# Create your models here.

class EditProfil(models.Model):
    # user = models.OneToOneField(User, on_delete=models.CASCADE, default='') # Delete profile when user is deleted
    namauser = models.ForeignKey(User, on_delete=models.CASCADE, related_name="namauser", null = True, blank = True)
    namadepan = models.CharField(max_length = 30, default = '', null = True)
    namabelakang = models.CharField(max_length = 30, default = '', null = True)
#Pekerjaan
    deskripsibisnis = models.TextField(default = '', null = True)
    deskripsisumber = models.TextField(default = '', null = True)
#Dokumen
    sid = models.IntegerField(default = '', null = True)
    noktp = models.IntegerField(default = '',null = True)
#Bank
    namabank = models.CharField(max_length=50, default = '', null = True)
    norekening = models.IntegerField(null = True)
    namapemilik = models.CharField(max_length=50, default = '', null = True)
#Preferensi

profil/forms.py
from django import forms
from .models import EditProfil

class moform(forms.ModelForm):
    class Meta:
        model = EditProfil
        fields ='__all__'

profil/views.py
from django.shortcuts import redirect, render
from .models import EditProfil
from .forms import moform
from django.views.generic import DetailView
from django.http.response import HttpResponse, HttpResponseRedirect
from django.http.response import HttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from astroid import context
from urllib3.util import request
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic
from django.utils.datastructures import MultiValueDictKeyError

@login_required
def datadiri_form(request):
    if request.method == 'POST':
        form = moform(request.POST or None, request.FILES or None)
        namadepan = request.POST.get('namadepan')
        namabelakang = request.POST.get('namabelakang')
        deskripsibisnis = request.POST.get('deskripsibisnis')
        deskripsisumber = request.POST.get('deskripsisumber')
        sid = request.POST.get('sid')
        noktp = request.POST.get('noktp')
        obj = EditProfil.objects.create(
            namadepan=namadepan, namabelakang=namabelakang, deskripsibisnis=deskripsibisnis, deskripsisumber=deskripsisumber, sid=sid, noktp=noktp)
        if obj:
            return redirect('/')
        return HttpResponse("")
        # if form.is_valid():
        # # save the form data to model
        #     form.save()
        # return HttpResponseRedirect('/')
    else:
        editprofil = EditProfil.objects.all()
        context = {
            'editprofil': editprofil
        }

    return render(request, 'bbbootstrap-snippet.html', context)

class UserEdit(generic.UpdateView):
    form_class = moform
    template_name = 'bbbootstrap-snippet.html'
    success_url = reverse_lazy('homepage')

    def get_object(self):
        return self.request.user

# def model_list(request):
#     profil = EditProfil.objects.all() # Mengambil seluruh Note yang ada di database
#     response = {'edit': edit} #notes: query set (list berisi model) --> bakal dimasukkan ke lab_2.html
#     return render(request, 'bbbootstrap-snippet.html', response)

profil/templates/Edit_profile_page.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% block content %}
<head>
    <meta charset="utf-8">
    <!--  This file has been downloaded from bootdey.com @bootdey on twitter -->
    <!--  All snippets are MIT license http://bootdey.com/license -->
    <title> YukInvest </title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <link href="https://netdna.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://netdna.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container bootstrap snippets bootdeys">
<div class="row">
  <div class="col-xs-12 col-sm-9">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="panel panel-default">
        <!-- Buat foto profil -->
        <div class="panel-body text-center">
          {{form.fotoprofil}}
          <img  src = "{{avatar.fotoprofil.url}}" class="img-circle profile-avatar" alt="User avatar">
        </div>
      </div>
      <div class="panel panel-default">
        <div class="panel-heading">
        <h4 class="panel-title">Data Diri</h4>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <label class="col-sm-2 control-label">Nama depan</label>
            <div class="col-sm-10"> {{form.namadepan}} </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Nama belakang</label>
            <div class="col-sm-10"> {{form.namabelakang}} </div>
          </div>
          <div _ngcontent-serverapp-c93="" class="input-group justify-between">
            <span _ngcontent-serverapp-c93="" class="input-disclaimer">*Saya menjamin bahwa informasi yang saya cantumkan diatas adalah benar dan siap bertanggung jawab atas segala konsekuensi yang terjadi di kemudian hari, serta memiliki kemampuan analisis risiko terhadap saham Penerbit dan memenuhi kriteria Pemodal sesuai peraturan yang berlaku.</span>
          </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
        <h4 class="panel-title">Pekerjaan</h4>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <label class="col-sm-2 control-label">Pendapatan Per Bulan</label>
            <div class="col-sm-10">
              {{form.pendapatan}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Sumber Pendapatan</label>
            <div class="col-sm-10">
              {{form.sumber}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Deskripsi Bisnis</label>
            <div class="col-sm-10">
              {{form.deskripsibisnis}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Deskripsi Sumber Pendapatan</label>
            <div class="col-sm-10">
              {{form.deskripsisumber}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Sumber Pendapatan</label>
            <div class="col-sm-10">
              {{form.sumber}}
            </div>
          </div>
          <div _ngcontent-serverapp-c93="" class="input-group justify-between">
            <span _ngcontent-serverapp-c93="" class="input-disclaimer">*Jika penghasilan Anda <= Rp 500.000.000,00 / tahun, maka maksimal investasi Anda 5% dari total penghasilan / tahun 
              **Jika penghasilan Anda > Rp 500.000.000,00 / tahun, maka maksimal investasi Anda 10% dari total penghasilan / tahun 
              ***Saya menjamin bahwa informasi yang saya cantumkan diatas adalah benar dan siap bertanggung jawab atas segala konsekuensi yang terjadi di kemudian hari, serta memiliki kemampuan analisis risiko terhadap saham Penerbit dan memenuhi kriteria Pemodal sesuai peraturan yang berlaku.</span>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
        <h4 class="panel-title">Dokumen</h4>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <label class="col-sm-2 control-label">No. SID</label>
            <div class="col-sm-10">
              {{form.sid}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">No. KTP</label>
            <div class="col-sm-10">
              {{form.noktp}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Foto Selfie</label>
            <div class="col-sm-10">
              {{form.fotoselfie}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Foto KTP</label>
            <div class="col-sm-10">
              {{form.fotoktp}}
            </div>
          </div>
          <div _ngcontent-serverapp-c93="" class="input-group justify-between">
            <span _ngcontent-serverapp-c93="" class="input-disclaimer">*Saya menjamin bahwa informasi yang saya cantumkan diatas adalah benar dan siap bertanggung jawab atas segala konsekuensi yang terjadi di kemudian hari, serta memiliki kemampuan analisis risiko terhadap saham Penerbit dan memenuhi kriteria Pemodal sesuai peraturan yang berlaku.</span>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
        <h4 class="panel-title">Bank</h4>
        </div>
        <div class="panel-body">
          <div class="form-group">
            <label class="col-sm-2 control-label">Nama Bank</label>
            <div class="col-sm-10">
              {{form.namabank}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Nomor Rekening</label>
            <div class="col-sm-10">
              {{form.norekening}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Nama Pemilik Rekening</label>
            <div class="col-sm-10">
              {{form.namapemilik}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Nama Ibu Kandung</label>
            <div class="col-sm-10">
              {{form.namaibu}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Nama Ahli Waris</label>
            <div class="col-sm-10">
              {{form.namaahliwaris}}
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label">Hubungan Ahli Waris</label>
            <div class="col-sm-10">
              {{form.ubahliwaris}}
            </div>
          </div>
          <div _ngcontent-serverapp-c93="" class="input-group justify-between">
            <span _ngcontent-serverapp-c93="" class="input-disclaimer">*Saya menjamin bahwa informasi yang saya cantumkan diatas adalah benar dan siap bertanggung jawab atas segala konsekuensi yang terjadi di kemudian hari, serta memiliki kemampuan analisis risiko terhadap saham Penerbit dan memenuhi kriteria Pemodal sesuai peraturan yang berlaku.</span>
          </div>
        </div>
      </div>

      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">Preferensi</h4>
          </div>
          <div class="panel-body">
            <div class="form-group">
              <label class="col-sm-2 control-label">Budget Investasi</label>
              <div class="col-sm-10">
                {{form.budgetinvestasi}}
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Tujuan Investasi</label>
              <div class="col-sm-10">
                {{form.tujuanInvestasi}}
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Preferensi Resiko Investasi</label>
              <div class="col-sm-10">
                {{form.resiko}}
              </div>
            </div>
            <div class="form-group">
              <label class="col-sm-2 control-label">Preferensi Peran</label>
              <div class="col-sm-10">
                {{form.prefperan}}
              </div>
            </div>
            <div _ngcontent-serverapp-c93="" class="input-group justify-between">
              <span _ngcontent-serverapp-c93="" class="input-disclaimer">*Saya menjamin bahwa informasi yang saya cantumkan diatas adalah benar dan siap bertanggung jawab atas segala konsekuensi yang terjadi di kemudian hari, serta memiliki kemampuan analisis risiko terhadap saham Penerbit dan memenuhi kriteria Pemodal sesuai peraturan yang berlaku.</span>
            </div>

          </div>
        </div>
          <div class="form-group">
          </div>
          <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
              <button type="submit" class="btn btn-primary">Submit</button>
              <button type="reset" class="btn btn-default">Cancel</button>
            </div>
          </div>
        </div>
    </form>
  </div>
</div>
</div>


{% endblock %}
<style type="text/css">

body{
    margin-top:20px;
    background:#f5f5f5;
}
/**
 * Panels
 */
/*** General styles ***/
.panel {
  box-shadow: none;
}
.panel-heading {
  border-bottom: 0;
}
.panel-title {
  font-size: 17px;
}
.panel-title > small {
  font-size: .75em;
  color: #999999;
}
.panel-body *:first-child {
  margin-top: 0;
}
.panel-footer {
  border-top: 0;
}

.panel-default > .panel-heading {
    color: #333333;
    background-color: transparent;
    border-color: rgba(0, 0, 0, 0.07);
}

form label {
    color: #999999;
    font-weight: 400;
}

.form-horizontal .form-group {
  margin-left: -15px;
  margin-right: -15px;
}
@media (min-width: 768px) {
  .form-horizontal .control-label {
    text-align: right;
    margin-bottom: 0;
    padding-top: 7px;
  }
}

.profile__contact-info-icon {
    float: left;
    font-size: 18px;
    color: #999999;
}
.profile__contact-info-body {
    overflow: hidden;
    padding-left: 20px;
    color: #999999;
}
.profile-avatar {
  width: 200px;
  position: relative;
  margin: 0px auto;
  margin-top: 196px;
  border: 4px solid #f3f3f3;
}
</style>
<script type="text/javascript">
</script>
</body>
</html>

profil/templates/bbbootstrap-snippet.html
<!doctype html>
                        <html>
                            <head>
                                <meta charset='utf-8'>
                                <meta name='viewport' content='width=device-width, initial-scale=1'>
                                <title> Profile - YukInvest </title>
                                <link href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css' rel='stylesheet'>
                                <link href='' rel='stylesheet'>
                                <script type='text/javascript' src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
                                <style>body {
    background: rgba(92, 122, 234, 0.28);
}

.form-control:focus {
    box-shadow: none;
    border-color: #5571DA;
}

.profile-button {
    background: #5C7AEA;
    box-shadow: none;
    border: none
}

.profile-button:hover {
    background: #3A61F3;
}

.profile-button:focus {
    background: #3A61F3;
    box-shadow: none
}

.profile-button:active {
    background: #3A61F3;
    box-shadow: none
}

.back:hover {
    color: #3A61F3;
    cursor: pointer
}

.labels {
    font-size: 11px
}
</style>
    </head>
    <body oncontextmenu='return false' class='snippet-body'>
    <div class="container rounded bg-white mt-5 mb-5">
    <form name = "Profil" method = 'POST'>
        {% csrf_token %}
            <div class="row">
                <div class="col-md-3 border-right">
                    <div class="d-flex flex-column align-items-center text-center p-3 py-5"><img class="rounded-circle mt-5" width="150px" src="https://st3.depositphotos.com/15648834/17930/v/600/depositphotos_179308454-stock-illustration-unknown-person-silhouette-glasses-profile.jpg"><span> </span></div>
                </div>
                <div class="col-md-5 border-right">
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right">Data Diri</h4>
                        </div>
                        <div class="row mt-2">
                            <div class="col-md-6"><label for = "namadepan" class="labels">Nama Depan</label>
                                <div class = "namadepan">
                                    {{ form.namadepan }}
                                </div>
                                <div class = "namadepan">
                                    <input type="text" class="form-control" placeholder="first name" name= "{{ forms.namadepan }}" id="id_{{ forms.namadepan }}"
                                    value="{{ forms.namadepan }}"> 
                                </div>   
                            </div>
                            <div class="col-md-6"><label for = "namabelakang" class="labels">Nama Belakang</label>
                                <div class = "namabelakang">
                                    {{ form.namabelakang }}
                                </div>
                                <div class = "namabelakang">
                                    <input type="text" class="form-control" placeholder="last name" name= "{{ forms.namabelakang }}" id="id_{{ forms.namabelakang }}"
                                    value="{{ forms.namabelakang }}">   
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="p-3 py-5">
                            <div class="mb-3">
                                <div class="col-md-12"><label for = "deskripsibisnis" class="labels">Deskripsi Bisnis</label>
                                    <div class = "deksripsibisnis">
                                        {{ form.deskripsibisnis }}
                                    </div>
                                    <div class = "deskripsibisnis">
                                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name= "{{ forms.deskripsibisnis }}" id="id_{{ forms.deskripsibisnis }}"
                                        value="{{ forms.deskripsibisnis }}"></textarea> 
                                    </div>
                            </div>
                            <div class="mb-3">
                                <div class="col-md-12"><label for = "deskripsisumber" class="labels">Deskripsi Sumber Pendapatan</label>
                                    <div class = "deskripsisumber">
                                        {{ form.deskripsisumber }}
                                    </div>
                                    <div class = "deskripsisumber" >
                                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name= "{{ forms.deskripsisumber }}" id="id_{{ forms.deskripsisumber }}"
                                        value="{{ forms.deskripsisumber }}"></textarea>
                                    </div>
                            </div>
                        </div>
                    </div>
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right">Dokumen</h4>
                        </div>
                        <div class="row mt-2">
                            <div class="col-md-6"><label for = "sid" class="labels">No. SID</label><input  type="text" class="form-control" placeholder="No. SID" name= "{{ forms.sid }}" id="id_{{ forms.sid }}"
                                value="{{ forms.sid }}"></div>
                            <div class="col-md-6"><label for = "noktp" class="labels">No. KTP</label><input  type="text" class="form-control" value="" placeholder="No.KTP" name= "{{ forms.noktp }}" id="id_{{ forms.noktp }}"
                                value="{{ forms.noktp }}"></div>
                        </div>
                    </div>
                    <div class="p-3 py-5">
                        <div class="d-flex justify-content-between align-items-center mb-3">
                            <h4 class="text-right">Bank</h4>
                        </div>
                        <div class="row mt-2">
                            <div name = "namabank">
                                {{ form.namabank }}
                            </div>
                            <div name = "namabank" class="col-md-6"><label class="labels">Nama Bank</label><input  type="text" class="form-control" placeholder="Nama Bank" name= "{{ forms.namabank }}" id="id_{{ forms.namabank }}"
                                value="{{ forms.namabank }}"></div>
                            <div name = "norekening">
                                {{ form.norekening }}
                            </div>
                            <div name = "norekening" class="col-md-6"><label class="labels">Nomor Rekening</label><input  type="text" class="form-control" placeholder="Nomor Rekening" name= "{{ forms.norekening}}" id="id_{{ forms.norekening }}"
                                value="{{ forms.norekening}}"></div>
                            <div name = "namapemilik">
                                {{ form.namapemilik }}
                            </div>
                            <div name = "namapemilik" class="col-md-6"><label class="labels">Nama Pemilik Rekening</label><input  type="text" class="form-control" placeholder="Nama Pemilik Rekening" name= "{{ forms.namapemilik}}" id="id_{{ forms.namapemilik}}"
                                value="{{ forms.namapemilik}}"></div>
                        </div>
                    </div>
                        <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="submit">Save Profile</button></div>
                </div>
            </div>
    </form>
</div>
</div>
</div>
<script type='text/javascript' src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js'></script>
<script type='text/javascript'>
    document.getElementById('sub-btn').addEventListener('click', function(e){
            e.preventDefault()
          })
          $('#sub-btn').click(function(e){
            namadepan = $('#id_namadepan').val()
            namabelakang = $('#id_namabelakang').val()
            deskripsibisnis = $('#id_deskripsibisnis').val()
            deskripsisumber = $('#id_deskripsisumber').val()
            sid = $('#id_sid').val()
            noktp = $('#id_noktp').val()
            namabank = $('#id_namabank').val()
            norekening = $('#id_norekening').val()
            namapemilik = $('#id_namapemilik').val()
            $.ajax({
              type: 'POST',
              url: `/profil/`,
              data: {
                'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val(),
                'namadepan': tittle,
                'namabelakang' : namabelakang,
                'deskripsibisnis' : deskripsibisnis, 
                'deskripsisumber' : deskripsisumber,
                'sid' : sid,
                'noktp': noktp,
                'namabank' : namabank,
                'norekening' : norekening,
                'namapemilik' : namapemilik
              },
              success: function (result) {
                $("#all-message").empty()
                getAllMessage()
              },
            });
          }); 
</script>
                            </body>
                            </html>

profil/templates/multiple.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save btn btn-default">Update</button>
</form>